language: bash

# allow for use of Docker-based workers
sudo: false

# --no-build because we has no Docker in Travis :)
script:
    - ./bashbrew/build.sh --no-build --all
    - ./bashbrew/push.sh --no-push --all
